Address race-condition on streaming api re-connect
It has been observed that when streaming connection is interrupted and FIG
instance may time-outs quicker than Falcon platform and in that case
FIG instance would not be able to re-discover the stream. We implement re-try
mechanism to allow for the streaming connection to time out on both ends.

Addressing the following behavior:
2021-04-13 07:55:50 fig cs_refresh DEBUG    Refresh of streaming session succeeded
2021-04-13 08:01:27 fig cs_stream  WARNING  Streaming Connection was closed.
2021-04-13 08:01:27 fig cs_stream  INFO     Thread requested to stop
2021-04-13 08:01:50 fig cs_mngmt   DEBUG    Restarting stream session
2021-04-13 08:01:52 fig cs_mngmt   ERROR    Could not restart stream session
Traceback (most recent call last):
  File "/fig/fig/falcon/stream.py", line 25, in run
    workers_died_event = self.start_workers()
  File "/fig/fig/falcon/stream.py", line 37, in start_workers
    for stream in falcon_api.streams(application_id):
  File "/fig/fig/falcon/api.py", line 32, in streams
    raise ApiError(
fig.falcon.api.ApiError: Falcon Streaming API not discovered. This may be caused by second instance of this application already running in your environment with the same application_id=fig-gcp, or by missing streaming API capability.