Handle race condition more gracefully (with multiple fig instances running)
Addressing:
Traceback (most recent call last):
  File "/fig/.local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 73, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/fig/.local/lib/python3.9/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/fig/.local/lib/python3.9/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.ALREADY_EXISTS
	details = "Requested entity already exists"
	debug_error_string = "{"created":"@XYZ","description":"Error received from peer ipv4:XYZ","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Requested entity already exists","grpc_status":6}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/fig/fig/worker.py", line 18, in run
    self.process_event(event)
  File "/fig/fig/worker.py", line 28, in process_event
    self.backends.process(falcon_event)
  File "/fig/fig/backends/__init__.py", line 30, in process
    runtime.process(falcon_event)
  File "/fig/fig/backends/gcp/__init__.py", line 200, in process
    Submitter(self.cache, falcon_event).submit()
  File "/fig/fig/backends/gcp/__init__.py", line 101, in submit
    self.submit_finding(finding)
  File "/fig/fig/backends/gcp/__init__.py", line 148, in submit_finding
    return self.cache.submit_finding(self.finding_id, finding, self.org_id)
  File "/fig/fig/backends/gcp/__init__.py", line 72, in submit_finding
    finding = self.scc.get_or_create_finding(finding_id, finding, self.source(org_id))
  File "/fig/fig/backends/gcp/api/scc.py", line 63, in get_or_create_finding
    return [self.create_finding(finding_id, finding, source)]
  File "/fig/fig/backends/gcp/api/scc.py", line 77, in create_finding
    created_finding = self.client.create_finding(
  File "/fig/.local/lib/python3.9/site-packages/google/cloud/securitycenter_v1/services/security_center/client.py", line 630, in create_finding
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/fig/.local/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/fig/.local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.AlreadyExists: 409 Requested entity already exists