Fix behaviour when stream session is not available
Interestingly, we get NoneType instead of emply list, when there are no
sessions:

Addressing:
2021-03-22 15:18:29 fig cs_mngmt   ERROR    Could not restart stream session
Traceback (most recent call last):
  File "/app/fig/falcon/stream.py", line 25, in run
    workers_died_event = self.start_workers()
  File "/app/fig/falcon/stream.py", line 37, in start_workers
    for stream in falcon_api.streams(application_id):
  File "/app/fig/falcon/api.py", line 34, in streams
    if 'resources' in body and len(body['resources']) > 0:
TypeError: object of type 'NoneType' has no len()