GCP SCC does not support severity='INFORMATIONAL'
Addressing:
fig worker-2   ERROR    Error occurred while processing event
Traceback (most recent call last):
  File "/fig/fig/worker.py", line 18, in run
    self.process_event(event)
  File "/fig/fig/worker.py", line 26, in process_event
    self.backends.process(falcon_event)
  File "/fig/fig/backends/__init__.py", line 38, in process
    runtime.process(falcon_event)
  File "/fig/fig/backends/gcp/__init__.py", line 216, in process
    Submitter(self.cache, falcon_event).submit()
  File "/fig/fig/backends/gcp/__init__.py", line 91, in submit
    finding = self.finding()
  File "/fig/fig/backends/gcp/__init__.py", line 115, in finding
    return Finding(
  File "/fig/.local/lib/python3.10/site-packages/proto/message.py", line 570, in __init__
    pb_value = marshal.to_proto(pb_type, value)
  File "/fig/.local/lib/python3.10/site-packages/proto/marshal/marshal.py", line 217, in to_proto
    pb_value = rule.to_proto(value)
  File "/fig/.local/lib/python3.10/site-packages/proto/marshal/rules/enums.py", line 56, in to_proto
    return self._enum[value].value
  File "/usr/local/lib/python3.10/enum.py", line 440, in __getitem__
    return cls._member_map_[name]
KeyError: 'INFORMATIONAL'