Provide empty default for chronicle.region config
Otherwise, the application will keep failing on start-up.

Addressing:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/configparser.py", line 789, in get
    value = d[option]
  File "/usr/local/lib/python3.9/collections/__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/lib/python3.9/collections/__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'region'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fig/fig/config/__init__.py", line 36, in validate
    self.get(section, var)
  File "/usr/local/lib/python3.9/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'region' in section: 'chronicle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/fig/fig/__main__.py", line 13, in <module>
    config.validate()
  File "/fig/fig/config/__init__.py", line 38, in validate
    raise Exception(
Exception: Please provide environment variable CHRONICLE_REGION or configuration option chronicle.region