Do not crash on missing zone_group
Addressing:
Traceback (most recent call last):
  File "/fig/fig/worker.py", line 18, in run
    self.process_event(event)
  File "/fig/fig/worker.py", line 26, in process_event
    self.backends.process(falcon_event)
  File "/fig/fig/backends/__init__.py", line 38, in process
    runtime.process(falcon_event)
  File "/fig/fig/backends/azure/__init__.py", line 86, in process
    Submitter(falcon_event).submit()
  File "/fig/fig/backends/azure/__init__.py", line 55, in submit
    post_data(self.workspace_id, self.primary_key, self.log(), 'FalconIntegrationGatewayLogs')
                                                   ^^^^^^^^^^
  File "/fig/fig/backends/azure/__init__.py", line 71, in log
    'ResourceGroup': self.event.device_details['zone_group']
                     ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'zone_group'